### ISSUE TITLE
Support reading archives

### ISSUE THREAD

**Issue by mdsteele** [jcreekmore/cpio-rs#2]
I'm working on a [library](https://github.com/mdsteele/rust-rpm) for reading and writing RPM packages, which use cpio archives internally, so I was hoping to use this crate.  Looks like it doesn't yet support reading cpio archives -- only writing them.  Is this something that could be added?  I'd be up for trying to implement that if you're open to a PR.

**Comment by jcreekmore** [comment]
Absolutely. I hadn't needed support for reading an archive yet, which is why I hadn't implemented it. If you have a need, I am definitely open to a PR to add that support.

**Comment by mdsteele** [comment]
Thanks, I'll try putting something together then.

**Comment by dralley** [comment]
Issue can be closed :)
